default_model: "gpt-4o-mini"
models:
  # OpenAI
  - name: "gpt-4o-mini"
    provider: "openai"
    model_id: "gpt-4o-mini"
  - name: "gpt-4o"
    provider: "openai"
    model_id: "gpt-4o"
  - name: "gpt-5.2"
    provider: "openai"
    model_id: "gpt-5.2"
  - name: "gpt-5-mini"
    provider: "openai"
    model_id: "gpt-5-mini"

  # Google Gemini
  - name: "gemini-3-pro"
    provider: "gemini"
    model_id: "gemini/gemini-3-pro"
  - name: "gemini-3-flash"
    provider: "gemini"
    model_id: "gemini/gemini-3-flash"
  - name: "gemini-2.5-flash"
    provider: "gemini"
    model_id: "gemini/gemini-2.5-flash"
  - name: "gemini-2.5-pro"
    provider: "gemini"
    model_id: "gemini/gemini-2.5-pro"
  - name: "gemini-3-flash-preview"
    provider: "gemini"
    model_id: "gemini/gemini-3-flash-preview"
  - name: "gemini-3-pro-preview"
    provider: "gemini"
    model_id: "gemini/gemini-3-pro-preview"

  # AWS Bedrock
  - name: "bedrock-claude-3-5-haiku"
    provider: "bedrock"
    model_id: "bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0"
  - name: "bedrock-claude-3-5-sonnet-v2"
    provider: "bedrock"
    model_id: "bedrock/us.anthropic.claude-3-7-sonnet-20250219-v1:0"
  - name: "bedrock-claude-4-6-sonnet"
    provider: "bedrock"
    model_id: "bedrock/us.anthropic.claude-sonnet-4-6"
  - name: "bedrock-claude-4-5-haiku"
    provider: "bedrock"
    model_id: "bedrock/us.anthropic.claude-haiku-4-5-20251001-v1:0"
  - name: "bedrock-qwen3"
    provider: "bedrock"
    model_id: "bedrock/qwen.qwen3-next-80b-a3b"
  - name: "bedrock-llama3"
    provider: "bedrock"
    model_id: "bedrock/meta.llama3-3-70b-instruct-v1:0"

  # Together AI
  - name: "together-qwen-next-80b"
    provider: "togetherai"
    model_id: "together_ai/Qwen/Qwen3-Next-80B-A3B-Instruct"
  - name: "together-gpt-oss-20b"
    provider: "togetherai"
    model_id: "together_ai/openai/gpt-oss-20b"
  - name: "together-gpt-oss-120b"
    provider: "togetherai"
    model_id: "together_ai/openai/gpt-oss-120b"


  # Local/OpenAI Compatible
  - name: "local-llm"
    provider: "openai_compatible"
    model_id: "local-model"
    api_base: "http://localhost:11434/v1"

  # OpenRouter
  - name: "openrouter-qwen-3.5-122b"
    provider: "openrouter"
    model_id: "openrouter/qwen/qwen3.5-122b-a10b"
  - name: "openrouter-qwen-3.5-flash-02-23"
    provider: "openrouter"
    model_id: "openrouter/qwen/qwen3.5-flash-02-23"
  - name: "openrouter-glm-4.7"
    provider: "openrouter"
    model_id: "openrouter/z-ai/glm-4.7"
  - name: "openrouter-glm-4.7-flash"
    provider: "openrouter"
    model_id: "openrouter/z-ai/glm-4.7-flash"
  - name: "openrouter-claude-4-5-sonnet"
    provider: "openrouter"
    model_id: "openrouter/anthropic/claude-sonnet-4.5"